// CONSTANTS_H
#pragma once

// --------------------------------------------

// Game constants
#define CONSTANTS_NONE -1
#define CONSTANTS_GAME_TITLE "Crown"

// Resources
#define CONSTANTS_RESOURCE_DIR "resources"

// VIDEO
#define CONSTANTS_VIDEO_SETTINGS_WIDTH_BUFFER 1280
#define CONSTANTS_VIDEO_SETTINGS_HEIGHT_BUFFER 800
#define CONSTANTS_VIDEO_SETTINGS_ENABLE_VSYNC 1
#define CONSTANTS_VIDEO_SETTINGS_ENABLE_WINDOW_HIGHDPI 1
#define CONSTANTS_VIDEO_SETTINGS_ENABLE_FULLSCREEN 0
#define CONSTANTS_VIDEO_SETTINGS_TARGET_FPS 144

// --------------------------------------------